[features]
all-features = true

[run]
timeout = "120s"
exclude-files = [
    "src/main.rs",
    "src/app/mod.rs",
    "src/decoder/mod.rs",
    "src/utils/mod.rs",
    "src/utils/threading.rs",
    "src/utils/errors.rs",
    "target/**",
]

[output]
formats = ["html", "xml"]

[report]
show-uncovered = true
