@echo off
chcp 65001 >nul
:: Image-Viewer Windows Installer
:: Universal installer for Windows 7/8/10/11 - no admin rights needed

setlocal EnableDelayedExpansion

echo =========================================
echo Image-Viewer Windows Installation
echo =========================================
echo.

:: Detect Windows version
for /f "tokens=4-5 delims=. " %%i in ('ver') do set WIN_VER=%%i

:: Set installation directory
:: Check if running from green/portable version (exe in parent dir)
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

if exist "%SCRIPT_DIR%\..\..\..\image-viewer.exe" (
    :: Green/portable version - use current location
    for %%F in ("%SCRIPT_DIR%\..\..\..") do set "INSTALL_DIR=%%~fF"
    set "INSTALL_DIR=%INSTALL_DIR:~0,-1%"
    set "PORTABLE_MODE=1"
    echo [Portable Mode] Detected green version
echo Installation directory: %INSTALL_DIR%
) else (
    :: Standard installation - use LocalAppData
    set "INSTALL_DIR=%LOCALAPPDATA%\Image-Viewer"
    set "PORTABLE_MODE=0"
    echo [Standard Mode] Installing to LocalAppData
echo Installation directory: %INSTALL_DIR%
    
    :: Create installation directory
    if not exist "%INSTALL_DIR%" (
        echo Creating installation directory...
        mkdir "%INSTALL_DIR%"
    )
    
    :: Copy executable
    if exist "%~dp0\..\..\target\release\image-viewer.exe" (
        echo Copying image-viewer.exe...
        copy /Y "%~dp0\..\..\target\release\image-viewer.exe" "%INSTALL_DIR%\" >nul
    ) else if exist "%~dp0\image-viewer.exe" (
        echo Copying image-viewer.exe...
        copy /Y "%~dp0\image-viewer.exe" "%INSTALL_DIR%\" >nul
    ) else (
        echo Warning: image-viewer.exe not found.
        echo Please build the project first with: cargo build --release
        pause
        exit /b 1
    )
)

set "EXE_PATH=%INSTALL_DIR%\image-viewer.exe"

:: Verify executable exists
if not exist "%EXE_PATH%" (
    echo Error: image-viewer.exe not found at %EXE_PATH%
    pause
    exit /b 1
)

echo.
echo Executable: %EXE_PATH%
echo.

:: Register context menu using HKEY_CURRENT_USER (universal, no admin needed)
echo Registering context menu for Windows %WIN_VER%...
echo Using HKEY_CURRENT_USER (no admin required)
echo.

:: Create temporary registry file with dynamic path
set "TEMP_REG=%TEMP%\image-viewer-install.reg"

(
echo Windows Registry Editor Version 5.00
echo.
echo ; Auto-generated by install.bat
echo ; Universal registry for Windows 7/8/10/11
echo ; Uses HKEY_CURRENT_USER (no admin required)
echo.
) > "%TEMP_REG%"

:: Generate registry entries for all supported image formats
for %%E in (png jpg jpeg gif webp tiff tif bmp ico heic heif avif) do (
    echo [HKEY_CURRENT_USER\Software\Classes\.%%E\shell\OpenWithImageViewer] >> "%TEMP_REG%"
    echo @="Open with Image-Viewer" >> "%TEMP_REG%"
    echo "Icon"="%EXE_PATH:\=\\%" >> "%TEMP_REG%"
    echo. >> "%TEMP_REG%"
    echo [HKEY_CURRENT_USER\Software\Classes\.%%E\shell\OpenWithImageViewer\command] >> "%TEMP_REG%"
    echo @=\"%EXE_PATH:\=\\%\" \"%%1\" >> "%TEMP_REG%"
    echo. >> "%TEMP_REG%"
)

:: Import registry
regedit /s "%TEMP_REG%"

if %errorlevel% neq 0 (
    echo.
    echo Error: Failed to register context menu.
    echo.
    del "%TEMP_REG%"
    pause
    exit /b 1
)

:: Clean up
del "%TEMP_REG%"

echo.
echo =========================================
echo Installation completed successfully!
echo =========================================
echo.
echo Image-Viewer installed to: %INSTALL_DIR%
echo.
if "%PORTABLE_MODE%"=="1" (
    echo [Portable Mode] No files were moved.
    echo The executable remains in its current location.
) else (
    echo [Standard Mode] Files installed to LocalAppData.
)
echo.
echo You can now right-click on image files to open with Image-Viewer.
echo.
echo Supported formats: PNG, JPG, JPEG, GIF, WebP, TIFF, TIF, BMP, ICO
echo                    HEIC, HEIF, AVIF
echo.
echo Note: This installer uses HKEY_CURRENT_USER and does NOT require
echo       Administrator privileges. It works on Windows 7/8/10/11.
echo.

pause
