@echo off
chcp 65001 >nul
:: Image-Viewer Context Menu Registration Script
:: Auto-detects installation directory and registers context menu

echo ==========================================
echo Image-Viewer Context Menu Registration
echo ==========================================
echo.

:: Get script directory and find image-viewer.exe
:: Try multiple possible locations (support both bundled and loose structures)
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

:: Check if exe is in the same directory as script
set "EXE_PATH=%SCRIPT_DIR%\image-viewer.exe"

:: If not found, try parent directories (for green/portable version structure)
:: Structure: install/windows/register-context-menu.bat -> ../../../image-viewer.exe
if not exist "%EXE_PATH%" (
    set "EXE_PATH=%SCRIPT_DIR%\..\..\..\image-viewer.exe"
)

:: Resolve full path
for %%F in ("%EXE_PATH%") do set "EXE_PATH=%%~fF"
for %%F in ("%EXE_PATH%") do set "INSTALL_DIR=%%~dpF"
set "INSTALL_DIR=%INSTALL_DIR:~0,-1%"

echo Detected installation path:
echo   %INSTALL_DIR%
echo.
echo Executable:
echo   %EXE_PATH%
echo.

:: Check if executable exists
if not exist "%EXE_PATH%" (
    echo [ERROR] image-viewer.exe not found!
    echo.
    echo Please ensure this script is placed in the same folder
    echo as the image-viewer.exe file.
    echo.
    pause
    exit /b 1
)

echo Registering context menu for supported image formats...
echo.

:: Create temporary registry file
set "TEMP_REG=%TEMP%\image-viewer-context-menu.reg"

(
echo Windows Registry Editor Version 5.00
echo.
echo ; Auto-generated by register-context-menu.bat
echo ; Installation path: %EXE_PATH%
echo.
) > "%TEMP_REG%"

:: Generate registry entries for each supported image format
for %%%%E in (png jpg jpeg gif webp tiff tif bmp ico heic heif avif) do (
    echo [HKEY_CURRENT_USER\Software\Classes\.%%%%E\shell\OpenWithImageViewer] >> "%TEMP_REG%"
    echo @="Open with Image-Viewer" >> "%TEMP_REG%"
    echo "Icon"="%EXE_PATH:\=\\%" >> "%TEMP_REG%"
    echo. >> "%TEMP_REG%"
    echo [HKEY_CURRENT_USER\Software\Classes\.%%%%E\shell\OpenWithImageViewer\command] >> "%TEMP_REG%"
    echo @=\"%EXE_PATH:\=\\%\" \"%%1\" >> "%TEMP_REG%"
    echo. >> "%TEMP_REG%"
)

:: Import registry file
echo Importing registry entries...
regedit /s "%TEMP_REG%"

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Failed to import registry!
    echo Please run this script as administrator if the error persists.
    echo.
    del "%TEMP_REG%"
    pause
    exit /b 1
)

:: Clean up
del "%TEMP_REG%"

echo.
echo ==========================================
echo Registration successful!
echo ==========================================
echo.
echo Context menu added for the following formats:
echo   - PNG, JPG, JPEG, GIF, WebP
echo   - TIFF, TIF, BMP, ICO
echo   - HEIC, HEIF, AVIF
echo.
echo You can now right-click any image file and select:
echo   "Open with Image-Viewer"
echo.
pause
