@echo off
chcp 65001 >nul
:: Image-Viewer Context Menu Registration Script
:: Universal for Windows 7/8/10/11 - no admin rights needed

echo ==========================================
echo Image-Viewer Context Menu Registration
echo ==========================================
echo.
echo Universal version for Windows 7/8/10/11
echo Uses HKEY_CURRENT_USER (no admin required)
echo.

:: Get script directory and find image-viewer.exe
:: Try multiple possible locations
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

:: Check multiple possible locations for the executable
set "EXE_PATH=%SCRIPT_DIR%\image-viewer.exe"

if not exist "%EXE_PATH%" (
    set "EXE_PATH=%SCRIPT_DIR%\..\..\..\image-viewer.exe"
)

if not exist "%EXE_PATH%" (
    set "EXE_PATH=%SCRIPT_DIR%\..\..\target\release\image-viewer.exe"
)

if not exist "%EXE_PATH%" (
    set "EXE_PATH=%LOCALAPPDATA%\Image-Viewer\image-viewer.exe"
)

:: Resolve full path
for %%F in ("%EXE_PATH%") do set "EXE_PATH=%%~fF"
for %%F in ("%EXE_PATH%") do set "INSTALL_DIR=%%~dpF"
set "INSTALL_DIR=%INSTALL_DIR:~0,-1%"

:: Check if executable exists
if not exist "%EXE_PATH%" (
    echo [ERROR] image-viewer.exe not found!
    echo.
    echo Searched locations:
    echo   - %SCRIPT_DIR%\image-viewer.exe
    echo   - %SCRIPT_DIR%\..\..\..\image-viewer.exe
    echo   - %SCRIPT_DIR%\..\..\target\release\image-viewer.exe
    echo   - %LOCALAPPDATA%\Image-Viewer\image-viewer.exe
    echo.
    echo Please ensure image-viewer.exe exists in one of these locations.
    echo.
    pause
    exit /b 1
)

echo Detected installation path:
echo   %INSTALL_DIR%
echo.
echo Executable:
echo   %EXE_PATH%
echo.

echo Registering context menu for supported image formats...
echo.

:: Create temporary registry file
set "TEMP_REG=%TEMP%\image-viewer-context-menu.reg"

(
echo Windows Registry Editor Version 5.00
echo.
echo ; Auto-generated by register-context-menu.bat
echo ; Universal registry for Windows 7/8/10/11
echo ; Uses HKEY_CURRENT_USER (no admin required)
echo.
) > "%TEMP_REG%"

:: Generate registry entries for each supported image format
for %%E in (png jpg jpeg gif webp tiff tif bmp ico heic heif avif) do (
    echo [HKEY_CURRENT_USER\Software\Classes\.%%E\shell\OpenWithImageViewer] >> "%TEMP_REG%"
    echo @="Open with Image-Viewer" >> "%TEMP_REG%"
    echo "Icon"="%EXE_PATH:\=\\%" >> "%TEMP_REG%"
    echo. >> "%TEMP_REG%"
    echo [HKEY_CURRENT_USER\Software\Classes\.%%E\shell\OpenWithImageViewer\command] >> "%TEMP_REG%"
    echo @=\"%EXE_PATH:\=\\%\" \"%%1\" >> "%TEMP_REG%"
    echo. >> "%TEMP_REG%"
)

:: Import registry file
echo Importing registry entries...
regedit /s "%TEMP_REG%"

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Failed to import registry!
    echo Please ensure you have write access to HKEY_CURRENT_USER.
    echo (Administrator privileges are NOT required)
    echo.
    del "%TEMP_REG%"
    pause
    exit /b 1
)

:: Clean up
del "%TEMP_REG%"

echo.
echo ==========================================
echo Registration successful!
echo ==========================================
echo.
echo Context menu added for the following formats:
echo   - PNG, JPG, JPEG, GIF, WebP
echo   - TIFF, TIF, BMP, ICO
echo   - HEIC, HEIF, AVIF
echo.
echo You can now right-click any image file and select:
echo   "Open with Image-Viewer"
echo.
echo Note: This script uses HKEY_CURRENT_USER and works on
echo       Windows 7, 8, 10, and 11 without admin rights.
echo.

pause
